AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: nodejs20.x
    CodeUri: src/functions

Resources:
  cardPayment:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: cardPayment.cardPayment
  cardNotPresentPayment:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: cardNotPresentPayment.cardNotPresentPayment
  cashPayment:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: cashPayment.cashPayment
  chequePayment:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: chequePayment.chequePayment
  postalOrderPayment:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: postalOrderPayment.postalOrderPayment
  confirm:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: confirm.confirm
  listReports:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: listReports.listReports
  generateReport:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: generateReport.generateReport
  checkReportStatus:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: checkReportStatus.checkReportStatus
  reverseCard:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: reverseCard.handler
  reverseCheque:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: reverseCheque.reverseCheque
  downloadReport:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: downloadReport.downloadReport
  groupPayment:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: groupPayment.groupPayment
