service: rsp-cpms-orchestration

frameworkVersion: ">=1.1.0 <2.0.0"
custom:
  documentation:
    version: '1'
    title: 'RSP CPMS Orchestration API'
    description: 'Api to handle and orchestrate calls to CPMS from RSP'

plugins:
  - serverless-offline
  - serverless-openapi-documentation
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
functions:
  authorizer:
    handler: handler.auth
    memorySize: 128
  decrypt:
    handler: handler.decrypt
    memorySize: 128
    events:
      -
        http:
          path: decrypt
          method: post
          authorizer: aws_iam
          cors: true
          documentation:
            summary: "Decrypt Token"
            description: "Decrypt Token"
            requestBody:
              description: "None"
            requestModels:
              application/json: "DecryptRequest"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "Message of successful Notification sent"
                responseModels:
                  application/json: "DecryptResponse"
              - statusCode: 400
                responseBody:
                  description: "Error message detailing why the token could not be decrypted"
                responseModels:
                  application/json: "ErrorResponse"
