import Constants from './constants';

export default (transactionData) => {
	console.log(transactionData);
	switch (transactionData.auth.scope) {
	case 'CARD':
		return {
			redirect_uri: transactionData.redirectUrl,
			total_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
			customer_reference: `${transactionData.paymentObject.penalty_reference}_${transactionData.paymentObject.penalty_type}`,
			scope: transactionData.auth.scope,
			customer_manager_name: Constants.customerManagerName,
			customer_name: Constants.customerName,
			customer_address: Constants.customerAddress,
			country_code: Constants.countryCode,
			payment_data: [{
				line_identifier: '1',
				amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				net_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_amount: Number(0.00).toFixed(2),
				allocated_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_code: 'O',
				tax_rate: '0',
				sales_reference: Constants.salesReference,
				product_reference: Constants.productReference,
				product_description: Constants.productDescription,
				invoice_date: new Date(Date.now()).toLocaleDateString(),
				receiver_name: Constants.receiverName,
				receiver_reference: Constants.receiverReference,
				receiver_address: Constants.receiverAddress,
				rule_start_date: '2018-03-01',
				deferment_period: '1',
				sales_person_reference: 'K',
				user_id: Constants.userId,
			}],
		};
	case 'CNP':
		return {
			redirect_uri: transactionData.redirectUrl,
			total_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
			customer_reference: `${transactionData.paymentObject.penalty_reference}_${transactionData.paymentObject.penalty_type}`,
			scope: transactionData.auth.scope,
			customer_manager_name: Constants.customerManagerName,
			customer_name: Constants.customerName,
			customer_address: Constants.customerAddress,
			country_code: Constants.countryCode,
			payment_data: [{
				line_identifier: '1',
				amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				net_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_amount: Number(0.00).toFixed(2),
				allocated_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_code: 'O',
				tax_rate: '0',
				sales_reference: Constants.salesReference,
				product_reference: Constants.productReference,
				product_description: Constants.productDescription,
				invoice_date: new Date(Date.now()).toLocaleDateString(),
				receiver_name: Constants.receiverName,
				receiver_reference: Constants.receiverReference,
				receiver_address: Constants.receiverAddress,
				rule_start_date: '2018-03-01',
				deferment_period: '1',
				sales_person_reference: 'K',
				user_id: Constants.userId,
			}],
		};
	case 'CASH':
		return {
			slip_number: transactionData.paymentObject.slip_number,
			batch_number: transactionData.paymentObject.batch_number,
			receipt_date: transactionData.paymentObject.receipt_date,
			redirect_uri: transactionData.redirectUrl,
			total_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
			customer_reference: `${transactionData.paymentObject.penalty_reference}_${transactionData.paymentObject.penalty_type}`,
			scope: transactionData.auth.scope,
			customer_manager_name: Constants.customerManagerName,
			customer_name: Constants.customerName,
			customer_address: Constants.customerAddress,
			country_code: Constants.countryCode,
			payment_data: [{
				line_identifier: '1',
				amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				net_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_amount: Number(0.00).toFixed(2),
				allocated_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_code: 'O',
				tax_rate: '0',
				sales_reference: Constants.salesReference,
				product_reference: Constants.productReference,
				product_description: Constants.productDescription,
				invoice_date: new Date(Date.now()).toLocaleDateString(),
				receiver_name: Constants.receiverName,
				receiver_reference: Constants.receiverReference,
				receiver_address: Constants.receiverAddress,
				rule_start_date: '2018-03-01',
				deferment_period: '1',
				sales_person_reference: 'K',
				user_id: Constants.userId,
			}],
		};
	case 'CHEQUE':
		return {
			slip_number: transactionData.paymentObject.slip_number,
			batch_number: transactionData.paymentObject.batch_number,
			receipt_date: transactionData.paymentObject.receipt_date,
			cheque_date: transactionData.paymentObject.cheque_date,
			cheque_number: transactionData.paymentObject.cheque_number,
			name_on_cheque: transactionData.paymentObject.name_on_cheque,
			redirect_uri: transactionData.redirectUrl,
			total_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
			customer_reference: `${transactionData.paymentObject.penalty_reference}_${transactionData.paymentObject.penalty_type}`,
			scope: transactionData.auth.scope,
			customer_manager_name: Constants.customerManagerName,
			customer_name: Constants.customerName,
			customer_address: Constants.customerAddress,
			country_code: Constants.countryCode,
			payment_data: [{
				line_identifier: '1',
				amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				net_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_amount: Number(0.00).toFixed(2),
				allocated_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_code: 'O',
				tax_rate: '0',
				sales_reference: Constants.salesReference,
				product_reference: Constants.productReference,
				product_description: Constants.productDescription,
				invoice_date: new Date(Date.now()).toLocaleDateString(),
				receiver_name: Constants.receiverName,
				receiver_reference: Constants.receiverReference,
				receiver_address: Constants.receiverAddress,
				rule_start_date: '2018-03-01',
				deferment_period: '1',
				sales_person_reference: 'K',
				user_id: Constants.userId,
			}],
		};
	case 'POSTAL_ORDER':
		return {
			slip_number: transactionData.paymentObject.slip_number,
			batch_number: transactionData.paymentObject.batch_number,
			receipt_date: transactionData.paymentObject.receipt_date,
			postal_order_number: transactionData.paymentObject.postal_order_number,
			redirect_uri: transactionData.redirectUrl,
			total_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
			customer_reference: `${transactionData.paymentObject.penalty_reference}_${transactionData.paymentObject.penalty_type}`,
			scope: transactionData.auth.scope,
			customer_manager_name: Constants.customerManagerName,
			customer_name: Constants.customerName,
			customer_address: Constants.customerAddress,
			country_code: Constants.countryCode,
			payment_data: [{
				line_identifier: '1',
				amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				net_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_amount: Number(0.00).toFixed(2),
				allocated_amount: transactionData.paymentObject.penalty_amount.toFixed(2),
				tax_code: 'O',
				tax_rate: '0',
				sales_reference: Constants.salesReference,
				product_reference: Constants.productReference,
				product_description: Constants.productDescription,
				invoice_date: new Date(Date.now()).toLocaleDateString(),
				receiver_name: Constants.receiverName,
				receiver_reference: Constants.receiverReference,
				receiver_address: Constants.receiverAddress,
				rule_start_date: '2018-03-01',
				deferment_period: '1',
				sales_person_reference: 'K',
				user_id: Constants.userId,
			}],
		};
	default:
		return null;
	}
};
